# Generated by Django 4.2.3 on 2023-08-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_user_address_user_email_user_fristname_user_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
