# Generated by Django 4.2.3 on 2023-08-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_car_remove_user_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
