# Generated by Django 4.2.3 on 2023-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_report_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
