# Generated by Django 4.2.3 on 2023-08-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0011_officer_age_officer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/pic'),
        ),
    ]
