# Generated by Django 4.2.3 on 2023-08-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0013_alter_officer_picture_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='picture',
            field=models.ImageField(default='ocr/static/ocr/pic', upload_to='ocr/static/ocr/pic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='ocr/static/ocr/pic', upload_to='ocr/static/ocr/pic'),
        ),
    ]
