# Generated by Django 4.2.3 on 2023-09-10 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0015_traffic_ticket_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='beneficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('picture_evidence', models.CharField(max_length=200, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.officer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.user')),
            ],
        ),
    ]
