# Generated by Django 4.2.3 on 2023-10-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0016_beneficial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='fristname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='report_problem',
            old_name='fristname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fristname',
            new_name='firstname',
        ),
    ]
