# Generated by Django 4.2.3 on 2023-10-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0017_rename_fristname_officer_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic_ticket',
            name='filePath',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
