# Generated by Django 4.2.3 on 2023-10-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0018_traffic_ticket_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_problem',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='report_problem',
            name='user',
        ),
    ]
