# Generated by Django 4.2.3 on 2023-10-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0019_remove_report_problem_officer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report_problem',
        ),
    ]
