# Generated by Django 4.2.3 on 2023-10-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0020_delete_report_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(max_length=10, null=True, upload_to='')),
                ('message', models.CharField(max_length=20, null=True)),
                ('pic_plate', models.ImageField(max_length=10, null=True, upload_to='')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.officer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.user')),
            ],
        ),
    ]
