# Generated by Django 4.2.3 on 2023-11-09 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0021_report_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_problem',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.officer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='./pic', upload_to='./pic'),
        ),
    ]
