# Generated by Django 4.2.3 on 2023-11-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0024_traffic_ticket_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='picture',
            new_name='picture_car',
        ),
    ]
