# Generated by Django 4.2.3 on 2023-11-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0027_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='traffic_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.car'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
