# Generated by Django 4.2.3 on 2023-11-10 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0028_payment_traffic_ticket_alter_notification_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.officer'),
        ),
    ]
