# Generated by Django 4.2.3 on 2023-11-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0029_notification_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.ImageField(max_length=250, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='photo_evidence',
            field=models.ImageField(max_length=250, null=True, upload_to=''),
        ),
    ]
