# Generated by Django 4.2.3 on 2023-11-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0031_alter_report_problem_pic_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='report_problem',
            name='pic_plate',
            field=models.ImageField(max_length=10, null=True, upload_to=''),
        ),
    ]
