# Generated by Django 4.2.3 on 2023-11-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0032_alter_payment_price_alter_report_problem_pic_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='tal',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
