# Generated by Django 4.2.3 on 2023-11-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0034_report_problem_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture_car',
            field=models.FileField(max_length=150, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='report_problem',
            name='license_plate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
