# Generated by Django 4.2.3 on 2023-11-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0035_alter_car_picture_car_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='beneficial',
            new_name='student_discipline',
        ),
    ]
