# Generated by Django 4.2.3 on 2023-11-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0036_rename_beneficial_student_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_discipline',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_discipline',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
