# Generated by Django 4.2.3 on 2023-11-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0037_student_discipline_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='tal',
            new_name='tel',
        ),
    ]
