# Generated by Django 4.2.3 on 2023-11-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0038_rename_tal_officer_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student_discipline',
            name='picture_evidence',
            field=models.FileField(max_length=150, null=True, upload_to=''),
        ),
    ]
