# Generated by Django 4.2.3 on 2023-11-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0039_alter_officer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
