# Generated by Django 4.2.3 on 2023-11-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0042_report_problem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_discipline',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
