# Generated by Django 4.2.3 on 2023-11-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0043_alter_notification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic_ticket',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
