# Generated by Django 4.2.3 on 2023-11-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0044_traffic_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
