# Generated by Django 4.2.3 on 2023-11-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0045_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
