# Generated by Django 4.2.3 on 2023-11-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0046_remove_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
