# Generated by Django 4.2.3 on 2023-11-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0047_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='photo_evidence',
            field=models.ImageField(max_length=250, null=True, upload_to='slip'),
        ),
    ]
