# Generated by Django 4.2.3 on 2023-11-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0048_alter_payment_photo_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='traffic_ticket',
        ),
        migrations.AddField(
            model_name='payment',
            name='traffic_ticket1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.traffic_ticket'),
        ),
    ]
