# Generated by Django 4.2.3 on 2023-11-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0049_remove_payment_traffic_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic_ticket',
            name='filePath',
            field=models.FileField(max_length=150, null=True, upload_to=''),
        ),
    ]
