# Generated by Django 4.2.3 on 2023-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0050_alter_traffic_ticket_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_plate_color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
