# Generated by Django 4.2.3 on 2023-11-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0051_car_license_plate_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
