# Generated by Django 4.2.3 on 2023-11-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0052_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='brand',
        ),
    ]
