# Generated by Django 4.2.3 on 2023-11-14 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0053_rename_model_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='province',
        ),
    ]
