# Generated by Django 4.2.3 on 2023-11-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0055_alter_car_picture_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_discipline',
            name='officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.officer'),
        ),
    ]
