# Generated by Django 4.2.3 on 2023-11-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0056_alter_student_discipline_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_problem',
            name='message',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
