# Generated by Django 4.2.3 on 2023-11-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0057_alter_report_problem_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='stack',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
