# Generated by Django 4.2.3 on 2023-11-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0059_notification_accusation'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
