# Generated by Django 4.2.3 on 2023-11-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0060_car_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='filePath',
            field=models.FileField(max_length=150, null=True, upload_to=''),
        ),
    ]
