# Generated by Django 4.2.3 on 2023-11-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0061_notification_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_problem',
            name='pic',
            field=models.ImageField(max_length=250, null=True, upload_to=''),
        ),
    ]
