# Generated by Django 4.2.3 on 2023-11-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0062_alter_report_problem_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_problem',
            name='license_plate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
