# Generated by Django 4.2.3 on 2023-11-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0063_alter_report_problem_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
