# Generated by Django 4.2.3 on 2024-01-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0064_alter_car_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_problem',
            name='pic_plate',
            field=models.ImageField(max_length=30, null=True, upload_to=''),
        ),
    ]
