# Generated by Django 4.2.3 on 2024-01-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0065_alter_report_problem_pic_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic_ticket',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
