# Generated by Django 4.2.3 on 2024-01-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0066_traffic_ticket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_problem',
            name='pic_plate',
            field=models.ImageField(max_length=250, null=True, upload_to=''),
        ),
    ]
