# Generated by Django 4.2.3 on 2024-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0067_alter_report_problem_pic_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stack',
            field=models.IntegerField(default=0, max_length=5, null=True),
        ),
    ]
